"""initial schema

Revision ID: 202608260001
Revises:
Create Date: 2026-08-26 00:00:00.000000
"""
import base64
import hashlib
import os
import secrets
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "202608260001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _hash_password(password: str) -> str:
    salt = secrets.token_bytes(16)
    value = hashlib.scrypt(password.encode(), salt=salt, n=2**14, r=8, p=1, dklen=32)
    return "scrypt$16384$8$1$%s$%s" % (
        base64.urlsafe_b64encode(salt).decode(),
        base64.urlsafe_b64encode(value).decode(),
    )


def _seed_accounts() -> None:
    """创建种子账号：admin 必建（否则无法登录管理）；demo 仅在 SEED_DEMO_PASSWORD 非空时创建。

    生产环境在 .env 中设置强密码 SEED_ADMIN_PASSWORD，并将 SEED_DEMO_PASSWORD 留空即可
    跳过演示账号。
    """
    users = sa.table(
        "user_account",
        sa.column("login", sa.String()),
        sa.column("name", sa.String()),
        sa.column("is_admin", sa.Boolean()),
        sa.column("password_hash", sa.String()),
    )
    rows = [
        {
            "login": "admin",
            "name": "系统管理员",
            "is_admin": True,
            "password_hash": _hash_password(os.getenv("SEED_ADMIN_PASSWORD", "admin-dev-only")),
        }
    ]
    demo_password = os.getenv("SEED_DEMO_PASSWORD", "demo-dev-only")
    if demo_password:
        rows.append(
            {
                "login": "demo",
                "name": "演示用户",
                "is_admin": False,
                "password_hash": _hash_password(demo_password),
            }
        )
    op.bulk_insert(users, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('project_type', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('parties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('started_date', sa.Date(), nullable=True),
    sa.Column('planned_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('planned_days', sa.Integer(), nullable=True),
    sa.Column('used_days', sa.Integer(), nullable=True),
    sa.Column('quality_issues', sa.Integer(), nullable=True),
    sa.Column('satisfaction', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('acceptance_result', sa.String(length=20), nullable=True),
    sa.Column('risk_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("project_type IN ('软件销售', '正版化服务', '正版化服务+软件销售')", name='ck_project_type'),
    sa.CheckConstraint("status IN ('active', 'archived', 'completed')", name='ck_project_status'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_project_progress'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_project_code', 'project', ['code'], unique=False)
    op.create_index('ix_project_customer_name', 'project', ['customer_name'], unique=False)
    op.create_index('ix_project_status', 'project', ['status'], unique=False)
    op.create_table('system_setting',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_login'), 'user_account', ['login'], unique=True)
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_expires_at'), 'auth_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_token_token_hash'), 'auth_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_token_user_id'), 'auth_token', ['user_id'], unique=False)
    op.create_table('project_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=False),
    sa.Column('target_project_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("link_type IN ('renewal', 'related')", name='ck_project_link_type'),
    sa.CheckConstraint('source_project_id < target_project_id', name='ck_project_link_canonical_pair'),
    sa.CheckConstraint('source_project_id <> target_project_id', name='ck_project_link_no_self'),
    sa.ForeignKeyConstraint(['source_project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_project_id', 'target_project_id', name='uq_project_link_pair')
    )
    op.create_index('ix_project_link_source_type', 'project_link', ['source_project_id', 'link_type'], unique=False)
    op.create_index('ix_project_link_target_type', 'project_link', ['target_project_id', 'link_type'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('manager', 'implementer')", name='ck_project_member_role'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_project_user')
    )
    op.create_index(op.f('ix_project_member_project_id'), 'project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_member_user_id'), 'project_member', ['user_id'], unique=False)
    op.create_table('snapshot',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("hash ~ '^[0-9a-f]{64}$'", name='ck_snapshot_sha256_hex'),
    sa.ForeignKeyConstraint(['parent_hash'], ['snapshot.hash'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('hash'),
    sa.UniqueConstraint('project_id', 'parent_hash', name='uq_snapshot_project_parent', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_snapshot_project_created', 'snapshot', ['project_id', 'created_at'], unique=False)
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('core_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contract_invoice_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_no', name='uq_summary_project_version')
    )
    op.create_index('ix_summary_project_created', 'summary', ['project_id', 'created_at'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('demo', 'report', 'meeting', 'audit', 'custom')", name='ck_tag_type'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    op.create_index('ix_tag_project_type', 'tag', ['project_id', 'type'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_task_status'),
    sa.CheckConstraint("task_type IN ('contract_recognition', 'summary_generation', 'summary_regeneration')", name='ck_task_type'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_status', 'task', ['status'], unique=False)
    op.create_index('ix_task_type_created', 'task', ['task_type', 'created_at'], unique=False)
    op.create_table('workspace_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_deliverable', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_file_project', 'workspace_file', ['project_id'], unique=False)
    op.create_index('ix_workspace_file_project_name', 'workspace_file', ['project_id', 'name'], unique=False)
    op.create_table('file_version',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('prev_version', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name='ck_file_version_content_hash_hex'),
    sa.CheckConstraint("document_type IS NULL OR document_type IN ('contract', 'invoice', 'payment', 'other')", name='ck_file_version_document_type'),
    sa.CheckConstraint("parse_status IN ('pending', 'processing', 'parsed', 'failed', 'skipped')", name='ck_file_version_parse_status'),
    sa.CheckConstraint("version ~ '^[0-9a-f]{64}$'", name='ck_file_version_sha256_hex'),
    sa.ForeignKeyConstraint(['file_id'], ['workspace_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prev_version'], ['file_version.version'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_hash'], ['snapshot.hash'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('version'),
    sa.UniqueConstraint('file_id', 'prev_version', name='uq_file_version_file_prev')
    )
    op.create_index('ix_file_version_document_type', 'file_version', ['document_type'], unique=False)
    op.create_index('ix_file_version_file_uploaded', 'file_version', ['file_id', 'uploaded_at'], unique=False)
    op.create_index('ix_file_version_prev', 'file_version', ['prev_version'], unique=False)
    op.create_index('uq_file_version_single_head', 'file_version', ['file_id'], unique=True, postgresql_where=sa.text('prev_version IS NULL'))
    op.create_table('contract_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('contract_no', sa.String(length=120), nullable=True),
    sa.Column('party_a', sa.String(length=255), nullable=True),
    sa.Column('party_b', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version'], ['file_version.version'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_contract_info_contract_no', 'contract_info', ['contract_no'], unique=False)
    op.create_index('ix_contract_info_signed_date', 'contract_info', ['signed_date'], unique=False)
    op.create_table('invoice_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('invoice_no', sa.String(length=120), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('seller', sa.String(length=255), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version'], ['file_version.version'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_invoice_info_invoice_no', 'invoice_info', ['invoice_no'], unique=False)
    op.create_index('ix_invoice_info_issued_date', 'invoice_info', ['issued_date'], unique=False)
    op.create_table('llm_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('file_version', sa.String(length=64), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('scene', sa.String(length=80), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scene = 'copilot_answer' AND num_nonnulls(task_id, file_version, summary_id, project_id) <= 1) OR (scene <> 'copilot_answer' AND num_nonnulls(task_id, file_version, summary_id, project_id) = 1)", name='ck_llm_call_single_owner'),
    sa.CheckConstraint("prompt_hash ~ '^[0-9a-f]{64}$'", name='ck_llm_call_prompt_hash'),
    sa.CheckConstraint('cost >= 0', name='ck_llm_call_cost'),
    sa.CheckConstraint('input_tokens >= 0 AND output_tokens >= 0', name='ck_llm_call_tokens'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_llm_call_latency'),
    sa.ForeignKeyConstraint(['file_version'], ['file_version.version'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_call_created_at', 'llm_call', ['created_at'], unique=False)
    op.create_index('ix_llm_call_model_created', 'llm_call', ['provider', 'model_name', 'created_at'], unique=False)
    op.create_index('ix_llm_call_scene_created', 'llm_call', ['scene', 'created_at'], unique=False)
    op.create_table('payment_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payer', sa.String(length=255), nullable=True),
    sa.Column('contract_no', sa.String(length=120), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version'], ['file_version.version'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_payment_info_contract_no', 'payment_info', ['contract_no'], unique=False)
    op.create_index('ix_payment_info_payment_date', 'payment_info', ['payment_date'], unique=False)
    op.create_table('snapshot_entry',
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['workspace_file.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_hash'], ['snapshot.hash'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version'], ['file_version.version'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_hash', 'file_id')
    )
    op.create_table('tag_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('file_version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_version'], ['file_version.version'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['workspace_file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'source_file_id', 'file_version', name='uq_tag_snapshot_version')
    )
    op.create_index('ix_tag_snapshot_file_version', 'tag_snapshot', ['file_version'], unique=False)
    op.create_index('ix_tag_snapshot_tag', 'tag_snapshot', ['tag_id'], unique=False)
    op.create_table('tracked_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('合同', '成本明细', '验收材料', '检测报告', '交付成果')", name='ck_tracked_file_category'),
    sa.ForeignKeyConstraint(['current_version'], ['file_version.version'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['workspace_file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracked_file_current_version', 'tracked_file', ['current_version'], unique=False)
    op.create_index('ix_tracked_file_project', 'tracked_file', ['project_id'], unique=False)
    op.create_index('uq_tracked_file_source', 'tracked_file', ['source_file_id'], unique=True, postgresql_where=sa.text('source_file_id IS NOT NULL'))
    op.create_table('summary_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('tracked_file_id', sa.Integer(), nullable=True),
    sa.Column('file_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_version'], ['file_version.version'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_file_id'], ['tracked_file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id', 'file_version', name='uq_summary_input_version')
    )
    op.create_index('ix_summary_input_file_version', 'summary_input', ['file_version'], unique=False)
    op.create_index('ix_summary_input_summary', 'summary_input', ['summary_id'], unique=False)
    # ### end Alembic commands ###
    _seed_accounts()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_summary_input_summary', table_name='summary_input')
    op.drop_index('ix_summary_input_file_version', table_name='summary_input')
    op.drop_table('summary_input')
    op.drop_index('uq_tracked_file_source', table_name='tracked_file', postgresql_where=sa.text('source_file_id IS NOT NULL'))
    op.drop_index('ix_tracked_file_project', table_name='tracked_file')
    op.drop_index('ix_tracked_file_current_version', table_name='tracked_file')
    op.drop_table('tracked_file')
    op.drop_index('ix_tag_snapshot_tag', table_name='tag_snapshot')
    op.drop_index('ix_tag_snapshot_file_version', table_name='tag_snapshot')
    op.drop_table('tag_snapshot')
    op.drop_table('snapshot_entry')
    op.drop_index('ix_payment_info_payment_date', table_name='payment_info')
    op.drop_index('ix_payment_info_contract_no', table_name='payment_info')
    op.drop_table('payment_info')
    op.drop_index('ix_llm_call_scene_created', table_name='llm_call')
    op.drop_index('ix_llm_call_model_created', table_name='llm_call')
    op.drop_index('ix_llm_call_created_at', table_name='llm_call')
    op.drop_table('llm_call')
    op.drop_index('ix_invoice_info_issued_date', table_name='invoice_info')
    op.drop_index('ix_invoice_info_invoice_no', table_name='invoice_info')
    op.drop_table('invoice_info')
    op.drop_index('ix_contract_info_signed_date', table_name='contract_info')
    op.drop_index('ix_contract_info_contract_no', table_name='contract_info')
    op.drop_table('contract_info')
    op.drop_index('uq_file_version_single_head', table_name='file_version', postgresql_where=sa.text('prev_version IS NULL'))
    op.drop_index('ix_file_version_prev', table_name='file_version')
    op.drop_index('ix_file_version_file_uploaded', table_name='file_version')
    op.drop_index('ix_file_version_document_type', table_name='file_version')
    op.drop_table('file_version')
    op.drop_index('ix_workspace_file_project_name', table_name='workspace_file')
    op.drop_index('ix_workspace_file_project', table_name='workspace_file')
    op.drop_table('workspace_file')
    op.drop_index('ix_task_type_created', table_name='task')
    op.drop_index('ix_task_status', table_name='task')
    op.drop_table('task')
    op.drop_index('ix_tag_project_type', table_name='tag')
    op.drop_index('ix_tag_name', table_name='tag')
    op.drop_table('tag')
    op.drop_index('ix_summary_project_created', table_name='summary')
    op.drop_table('summary')
    op.drop_index('ix_snapshot_project_created', table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_index(op.f('ix_project_member_user_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_project_id'), table_name='project_member')
    op.drop_table('project_member')
    op.drop_index('ix_project_link_target_type', table_name='project_link')
    op.drop_index('ix_project_link_source_type', table_name='project_link')
    op.drop_table('project_link')
    op.drop_index(op.f('ix_auth_token_user_id'), table_name='auth_token')
    op.drop_index(op.f('ix_auth_token_token_hash'), table_name='auth_token')
    op.drop_index(op.f('ix_auth_token_expires_at'), table_name='auth_token')
    op.drop_table('auth_token')
    op.drop_index(op.f('ix_user_account_login'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('system_setting')
    op.drop_index('ix_project_status', table_name='project')
    op.drop_index('ix_project_customer_name', table_name='project')
    op.drop_index('ix_project_code', table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
